# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-28 10:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodtruck', '0002_delete_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='title',
            field=models.CharField(default='new', max_length=255),
            preserve_default=False,
        ),
    ]
